version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: nexus-postgres
    restart: always
    environment:
      POSTGRES_USER: nexus
      POSTGRES_PASSWORD: nexus_password_dev
      POSTGRES_DB: nexus_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
